# See https://docs.docker.com/samples/library/gcc/ for more on how to use this 
# image
FROM gcc:latest

# Update apps on the base image
RUN apt-get -y update && apt-get install -y

# Install Python
RUN apt-get install python -y

# These commands copy your files into the specified directory in the image
# and set that as the working location
COPY . /usr/src/gcc-build
WORKDIR /usr/src/gcc-build

# This command compiles your app using GCC, adjust for your source code
RUN g++ -o Automate src/App.cpp

# This command runs your application, comment out this line to compile only
CMD ["./Automate"]

LABEL Name=Automate Version=0.0.1
